### PR TITLE
Proper and secure cli-server router

### PR DESCRIPTION
**Pull request by szepeviktor**
@nylen ~~else+return may not be a livable solution~~

### CODE REVIEW

**Comment by nylen** [comment]
Checking the sapi name is fine, but the `return` change breaks the router when requesting a directory:

2019-07-01T23 54 39-05 00

The way this is written is correct - the pattern is "serve index.php, or serve a .json file, or fall back to the cli-server's default behavior."  With this PR we do "serve index.php and then try to fall back to the default behavior" instead.

Also, we do not expose this file in our webservers so this is not very urgent.

**Comment by szepeviktor** [comment]
Excuse me. I haven't noticed the main `if` branch has no termination.

**Comment by nylen** [comment]
Looks good now. Thanks for the PR :)

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
