### PR TITLE
Importers API endpoint

### PR DESCRIPTION
**Pull request by viktorix**
Fixes issue #55. This adds a new API endpoint, which returns a JSON list of importer plugins. 

WordPress API endpoint:
https://api.wordpress.org/core/importers/1.1/

To keep the code consistent, I used migrations endpoint code to generate JSON list. Not sure if this is the best way, but it seems to do the job and keep API code consistent.

### CODE REVIEW

**Comment by mattyrob** [comment]
As this is out first version of the API we can name it `1.0` rather than `1.1` can't we?

**Comment by viktorix** [comment]
@mattyrob WordPress has version 1.0, which returns serialized data but it's not used in the core:
https://codex.wordpress.org/WordPress.org_API#Popular_Import_Plugin
https://api.wordpress.org/core/importers/1.0/

That's why I just kept the version number, not to confuse. But, I'm happy to change it to 1.0 if you think this is not relevant.

**Comment by bahiirwa** [comment]
@viktorix it should be 1.0 since this is on the ClassicPress side now. The api URL will be changing

**Comment by viktorix** [comment]
I've updated the directory name to 1.0, so the API is now version 1.0.

**Review by mattyrob — APPROVED** [review]

**Review by bahiirwa — APPROVED** [review]
LGTM. Good to have this on remote for the project.

**Pull request merged**
